export const typesValue: string[] = [
  "Acid Plant",
  "Artificially generated world",
  "Arcade",
  "Asteroid",
  "Base",
  "Box",
  "Consciousness",
  "Country",
  "Customs",
  "Daycare",
  "Death Star",
  "Diegesis",
  "Dimension",
  "Dream",
  "Dwarf planet (Celestial Dwarf)",
  "Elemental Rings",
  "Fantasy Town",
  "Game",
  "Hell",
  "Human",
  "Liquid",
  "Machine",
  "Memory",
  "Menagerie",
  "Microverse",
  "Mount",
  "Nightmare",
  "Non-Diegetic Alternative Reality",
  "Planet",
  "Police department",
  "Quadrant",
  "Quasar",
  "Resort",
  "Reality",
  "Space",
  "Spacecraft",
  "Woods",
  "Space Station",
  "Spa",
  "Teenyverse",
  "TV",
  "Unknown",
];

export const dimensionsValue: string[] = [
  "Chair Dimension",
  "Cromulon Dimension",
  "Cronenberg Dimension",
  "Dimension C-137",
  "Dimension C-35",
  "Dimension C-500A",
  "Dimension D-716",
  "Dimension D-716-B",
  "Dimension D-716-C",
  "Dimension D-99",
  "Dimension J19ζ7",
  "Dimension J-22",
  "Dimension K-22",
  "Dimension K-83",
  "Dimension 5-126",
  "Eric Stoltz Mask Dimension",
  "Evil Rick's Target Dimension",
  "Fantasy Dimension",
  "Fascist Dimension",
  "Fascist Shrimp Dimension",
  "Fascist Teddy Bear Dimension",
  "Giant Telepathic Spiders Dimension",
  "Pizza Dimension",
  "Magic Dimension",
  "Merged Dimension",
  "Replacement Dimension",
  "Phone Dimension",
  "Post-Apocalyptic Dimension",
  "Testicle Monster Dimension",
  "Tusk Dimension",
  "Wasp Dimension",
  "Unknown",
  "Unknown dimension",
];
