import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Irish_Grover } from "next/font/google";
import styles from "./page.module.css";
import "./globals.css";

const irish = Irish_Grover({
  subsets: ["latin"],
  weight: "400",
  variable: "--irish-glover",
});

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={irish.className}>
        <header className={styles.header}>
          <nav className={styles.navigation}>
            <Link href="/">
              <Image
                src="/favicon.png"
                width={46}
                height={46}
                alt="Rick and Morty logo"
                priority={true}
              />
            </Link>

            <ul className={styles.list}>
              <li className={styles.item}>
                <Link href="/character">Character</Link>
              </li>
              <li className={styles.item}>
                <Link href="/location">Location</Link>
              </li>
              <li className={styles.item}>
                <Link href="/episode">Episode</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer className={styles.footer}>
          <p className={styles.footerText}>
            <span>Make with</span>
            <Image
              src="/heart.svg"
              width={16}
              height={16}
              alt="Rick and Morty logo"
              priority={true}
            ></Image>{" "}
            <span>for the MobProgramming team</span>
          </p>
        </footer>
      </body>
    </html>
  );
}
