import type { Metadata } from "next";
import { Irish_Grover } from "next/font/google";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const inter = Irish_Grover({
  subsets: ["latin"],
  weight: "400",
  variable: "--irish-glover",
});

const montserat = Montserrat_Alternates({
  subsets: ["latin"],
  weight: "700",
  variable: "--montserat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
